server:
  port: 8090

spring:
  rabbitmq:
     addresses: localhost:5672
     password: guest
     username: guest
     listener:
       simple:
         concurrency: 4
         max-concurrency: 8
         prefetch: 162
       concurrency: 4
       max-concurrency: 8
       prefetch: 162
  cloud:
    function:
      stream:
        processor:
          name: uppercase
      scan:
        packages: com.punjab.de.janwar.stream.service.consumer.functions
      definition: foodorder
    stream:
      default:
        contentType: application/json
      bindings:
        foodorder-in-0:
          destination: foodOrders
          group: eaters
        foodordersupplier-out-0:
          destination: foodOrders
      rabbit:
        bindings:
          foodOrdersChannel:
            producer:
              bindingRoutingKey:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false

metadata.store.jdbc.table-prefix: rabbit_

spring.h2.console.enabled: true
spring.h2.console.path: /h2

eureka:
  client:
    enabled: false

security:
  ignored: /**